### ISSUE TITLE
[bug] phero/server no such file or directory

### ISSUE THREAD

**Issue by draylegend** [phero-hq/phero#103]
[Repro (video)](https://youtu.be/Ozu4Rsr5WaQ)

### Error

```js
npx phero@next init server
Ready to go! Run `npx phero` again to continue.

npx phero@next
phero-server @ . ✖ Could not build RPC's

    ENOENT: no such file or directory, open 'D:\dev\web\tests\phero\api\dist\phero-execution.js'
```

### ENV

```
@phero/server 0.9.14-alpha.1
typescript 4.9.5
node 18.12.1
npm 9.4.1
```

**Comment by Jpunt** [comment]
@draylegend thanks for the clear reproduction video 👍 Your issue should be fixed by following the extra tsconfig-change outlined in the docs: 

> At this moment, there is an additional step of configuration needed. Add these lines to the tsconfig.json of your server:
> 
> {
>   "compilerOptions": {
>     ...
>     "rootDir": "src",
>     "outDir": "dist"
>   }
> }
> 
> We're working on a fix for this, so you won't have to do this. 

This is something high in our list to be fixed next. Let me know if this doesn’t solve the issue.

**Comment by draylegend** [comment]
@Jpunt my bad, forgot the additional step regarding `tsconfig`. Everything works fine!
