### ISSUE TITLE
Support export of arrow function in service

### ISSUE THREAD

**Issue by jim-lub** [phero-hq/phero#63]
Exporting an arrow function in a service throws a Samen error. We should support this functionality.

```
import { createService } from "@samen/server"

const aad = async (): Promise<void> => {}

export const aadService = createService({
  aad,
})
```

```
S145: ParserModel not implemented yet: `async (): Promise<void> => { }` (kind:214)
```

**Comment by kamilafsar** [comment]
With the release of v0.10.0 this should be fixed. Closing this ticket. Please reopen if you still encounter issues.
