### ISSUE TITLE
Export type alias and interface (see example)

### ISSUE THREAD

**Issue by jim-lub** [phero-hq/phero#70]
We don't properly export an interface or type alias when used as examples:
```
interface Topic {
  aad: string
}

export async function aad(): Promise<(Topic & { prop: any })[]> {
  // content
}
```
or
```
type Topic = {
  aad: string
}

export async function aad(): Promise<(Topic & { prop: any })[]> {
  // content
}
```

Error message:
```
messageText: "Return type of exported function has or is using private name 'Topic'."
```

___
Until fixed this is a workaround:
```
export interface ListTopic extends Topic {
  props: any
}

export async function aad(): Promise<{
  topics: ListTopic[]
}> {
  // content
}
```

**Comment by jim-lub** [comment]
The previous mentioned workaround was actually throwing another unrelated error. So I've updated the workaround with a working one.

**Comment by kamilafsar** [comment]
With the release of v0.10.0 this should be fixed. Closing this ticket. Please reopen if you still encounter issues.
