### ISSUE TITLE
S145: ParserModel not implemented yet (kind:178)

### ISSUE THREAD

**Issue by parweb** [phero-hq/phero#77]
I think I find a bug or missing feature

in my phero.ts file
I've got

```ts
import { createService } from '@phero/server';

type Id = number | string;

interface User {
  id: Id;
  email: string;
}

async function update(data: Partial<User>): Promise<User> {
  return { id: 1, email: 'plop@email.com' };
}

export const user = createService({ update });
```

but got an error 

```
error TS-PheroError:
S145: ParserModel not implemented yet: `Id` (kind:178)
```

When I debug the code I find the problematic line

```Partial<User>``` on ```async function update(data: Partial<User>): Promise<User> {```

indeed if we change ```Partial<User>```  to ```User```  for example everything is ok

Is it an known bug ?

**Comment by kamilafsar** [comment]
Just tested this, I can confirm this is a bug. 
I'll try to fix this asap.

**Comment by kamilafsar** [comment]
Fix is on its way @parweb 
https://github.com/phero-hq/phero/pull/78

**Comment by parweb** [comment]
nice

**Comment by kamilafsar** [comment]
@parweb Just released 0.9.11.
You should update both @phero/server and @phero/client and run Phero with the `npx phero@latest` command.
Can you please confirm if the issue is resolved for you? Thanks in advance :)

**Comment by parweb** [comment]
let's test this

**Comment by parweb** [comment]
It's working

I found an another bug will open a new issue

**Comment by kamilafsar** [comment]
Thanks for reporting. 

Sorry to hear you stumbled upon another bug. Lets see how fast we can fix that one :)

**Comment by parweb** [comment]
No worries it's for a hobby project love the phylosophy of your tool 👍
Happy to help stabalize it
