### ISSUE TITLE
Support `Exclude` on interface property

### ISSUE THREAD

**Issue by jim-lub** [phero-hq/phero#83]
Using `Exclude` on an interface property throws an error.

Example:
```
export enum Friends {
  Kamil = "Kamil",
  Jasper = "Jasper",
  Jim = "Jim",
}

export interface Aad {
  best_friend: Exclude<Friends, Friends.Jim>
}
```

Error:
```
Cannot read properties of undefined (reading 'parent')
```

___

We do support `Exclude` in different situations tho. This works just fine for example:
```
export type Aad = Exclude<Friends, Friends.Jim>
```

**Comment by kamilafsar** [comment]
With the release of v0.10.0 this should be fixed. Closing this ticket. Please reopen if you still encounter issues.
